CREATE TABLE IF NOT EXISTS user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar UNIQUE,
    login varchar UNIQUE,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id int REFERENCES user ON DELETE CASCADE,
    friend_id int REFERENCES user ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar(200),
    release_date date,
    duration int,
    mpa_id int REFERENCES mpa
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id int REFERENCES film ON DELETE CASCADE,
    genre_id int REFERENCES genre ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_like (
    film_id int REFERENCES film ON DELETE CASCADE,
    user_id int REFERENCES user ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);
